### PR TITLE
Add license comments

### PR DESCRIPTION
**Pull request by shinnn**
When we use CSS compressors such as [clean-css](https://github.com/GoalSmashers/clean-css), we can preserve license comments wrapped with `/*! ... */`.

### CODE REVIEW

**Comment by simonwhitaker** [comment]
Thanks! (Just found this in my PR queue, I'd managed to miss it. Sorry it took so long to merge.)

**Comment by shinnn** [comment]
No problem!
And, I'll be glad if you publish the new release (maybe, a patch release v0.1.1) for Bower.

**Comment by simonwhitaker** [comment]
@shinnn No problem. Do I just need to update the version number(s) in the repo, or is there something I need to do at Bower's end, do you know? (I don't use Bower, support for it was added by another of this repo's many awesome contributors. :smile:)

**Comment by simonwhitaker** [comment]
Looks like just updating the repo is enough.

``` shell
$ bower info github-fork-ribbon-css                  
bower github-fork-ribbon-css#*  cached git://github.com/simonwhitaker/github-fork-ribbon-css.git#1.0.0
bower github-fork-ribbon-css#*         validate 1.0.0 against git://github.com/simonwhitaker/github-fork-ribbon-css.git#*
bower github-fork-ribbon-css#*              new version for git://github.com/simonwhitaker/github-fork-ribbon-css.git#*
bower github-fork-ribbon-css#*          resolve git://github.com/simonwhitaker/github-fork-ribbon-css.git#*
bower github-fork-ribbon-css#*         download https://github.com/simonwhitaker/github-fork-ribbon-css/archive/0.1.1.tar.gz
bower github-fork-ribbon-css#*          extract archive.tar.gz
bower github-fork-ribbon-css#*         resolved git://github.com/simonwhitaker/github-fork-ribbon-css.git#0.1.1

{
  name: 'github-fork-ribbon-css',
  version: '0.1.1',
  homepage: 'http://simonwhitaker.github.io/github-fork-ribbon-css/',
  authors: [
    'Simon Whitaker'
  ],
  description: '"Fork me on GitHub" CSS ribbon',
  main: [
    'gh-fork-ribbon.css',
    'gh-fork-ribbon.ie.css'
  ],
  keywords: [
    'css',
    'fork',
    'GitHub',
    'ribbon'
  ],
  license: 'MIT',
  ignore: [
    '**/.*',
    'node_modules',
    'bower_components',
    'test',
    'tests'
  ]
}

Available versions:
  - 0.1.1
  - 0.1.0

You can request info for a specific version with 'bower info github-fork-ribbon-css#<version>'
```

Cool! :smile:

**Comment by shinnn** [comment]
Great!
Thanks for merging and quick release.

**Pull request merged**
