### PR TITLE
Move CSS into seperate stylesheets.

### PR DESCRIPTION
**Pull request by neersighted**
I went and split the CSS into separate files so this can be easily included in other projects.

### CODE REVIEW

**Comment by simonwhitaker** [comment]
Thanks! There's a typo in your CSS filenames though ("robbon" instead of ribbon) – want to tweak that and update the pull request?

**Comment by neersighted** [comment]
No problem.

**Comment by neersighted** [comment]
I can rebase them into one commit if you like.

**Comment by simonwhitaker** [comment]
Merged – thanks! Bring on your fixes for #2, #3 :-)

**Pull request merged**
