### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by XhmikosR**
I can add normalize.css in the repository if you prefer that approach.

I also think we should move the inline CSS to a demo.css maybe.

What do you think?

### CODE REVIEW

**Comment by simonwhitaker** [comment]
What does normalize.css do? (Thanks for these pull requests, I'm learning so much! :smile:)

**Comment by XhmikosR** [comment]
http://necolas.github.io/normalize.css/

**Comment by XhmikosR** [comment]
PR updated.

**Comment by simonwhitaker** [comment]
Just found this still in my queue. Since January!! So sorry it took me this long to merge, and many thanks for the contribution.

**Comment by XhmikosR** [comment]
No worries, thanks for the merge!

**Pull request merged**
